services:
  - type: web
    name: smart-banking-system
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements-dev.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
